### ISSUE TITLE
Functions to calculate Z_Min, Z_Max, Z_Mean

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/slopes#19]
From #10

**Comment by temospena** [comment]
hey @Robinlovelace ,
just added the `z_mean`, `z_max `and `z_min `functions. https://github.com/ITSLeeds/slopes/commit/6b93aaa2c277cacc69cf77027ff45ac9103b25db
`z_direction` still missing (related to #20)

I'm not sure about `@rdname` s, can you please check?

**Comment by Robinlovelace** [comment]
Great work @temospena ! Will take a look now.

**Comment by Robinlovelace** [comment]
> I'm not sure about `@rdname` s, can you please check?

Just checked and updated in https://github.com/ITSLeeds/slopes/commit/9f4769453bbc9adda98eefe49ff9e8ab74a41d48

Basically `@rdname` is used to make one help page (`slope_z_value` in this case) be used by many functions. It's good if functions are very similar as is the case here and is a bit lazy because it means less typing of documentation code... Looking good!
