### ISSUE TITLE
slope_xyz

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/slopes#23]
Looking at the docs I don't think there is a function to get slopes directly from linestrings with xyz geometries, e.g.:

```r
slope_xyz(slopes::lisbon_road_segment_3d)
```

should work.

**Comment by temospena** [comment]
> Looking at the docs I don't think there is a function to get slopes directly from linestrings with xyz geometries, e.g.:
> 
> ```r
> slope_xyz(slopes::lisbon_road_segment_3d)
> ```
> 
> should work.

This is working.

``` r
library(slopes)
slope_xyz(slopes::lisbon_road_segment_3d)
#>          1 
#> 0.09501323
```

**Comment by Robinlovelace** [comment]
Great to see! We should now be able to continue with the evaluation based on the Seattle data (in addition to the existing data from Lisbon/Arc). Something like the following should work...

```r
magnolia_3d = slope_3d(magnolia)
slope_xyz(magnolia_3d)
```

**Comment by Robinlovelace** [comment]
Plus more tests #18... Can find time these eve after ideas + :beers: !

**Comment by Robinlovelace** [comment]
Assuming you're happy with this @temospena, closing for now. We can always change function names.
