### ISSUE TITLE
Idea: optionally auto download elevation data if none provided

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/slopes#6]
E.g. using https://github.com/jhollist/elevatr

**Comment by mpadge** [comment]
See [this comment](https://github.com/jhollist/elevatr/issues/20#issuecomment-617945404) in `elevatr`, from which i can now confirm that the procedure can be automated. I have a prototype function in [`osmdata`](https://github.com/ropensci/osmdata/blob/master/R/elevation.R#L85-L104) to get tile IDs, but it's not quite right. Auto-download was not possible when i developed that, but now is, so the whole procedure can be easily automated.
